advancedtelematic/quickcheck-state-machine

src/Test/QuickCheck/StateMachineModel.hs, src/Test/QuickCheck/StateMachineModel/Example.hs
Actually making use of the typed returnsRef (to avoid unsafeCoerce), requires some more work though...
=> Add a typed returnsRef variant to RefKit.

example/src/MutableReference.hs, src/Test/StateMachine.hs, src/Test/StateMachine/Internal/Parallel.hs
Limited benchmarks seems to suggest this actually makes things faster,
but more importantly we don't need some annoying Eq and Ord instances!
=> Stop removing duplicates with Set.{toList, fromList} when shrinking.

.hlint.yaml
The file ignores the two suggestions we didn't find useful.
=> Add a .hlint.yaml file.

README.md, quickcheck-state-machine.cabal, src/Test/StateMachine/Internal/Parallel.hs, src/Test/StateMachine/Internal/Utils/BoxDrawer.hs
Example output:
```
> quickCheck $ MutableReference.prop_parallel RaceCondition 
*** Failed! Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable (after 5 tests and 6 shrinks): 
Fork [Inc (IntRef (Ref 0) (Pid 0)) ()] [New (IntRef (Ref 0) (Pid 0))] [Inc (IntRef (Ref 0) (Pid 0)) (),Read (IntRef (Ref 0) (Pid 0)) ()]
Couldn't linearise:
Prefix: 
New --> $0
Parallel:
│ ┌────────┐
│ │Inc $0  │
┌────────┐ │ │        │
│Inc $0  │ │ │        │
│  --> ()│ │ │        │
└────────┘ │ │        │
│ │  --> ()│
│ └────────┘
│ ┌────────┐
│ │Read $0 │
│ │   --> 1│
│ └────────┘
```
new output
```
> quickCheck $ MutableReference.prop_parallel RaceCondition 
*** Failed! Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable, Falsifiable, …
```
=> Use BoxDrawings for parallel case

example/src/DieHard.hs, example/src/TicketDispenser.hs, example/src/UnionFind.hs, src/Test/StateMachine/Types.hs
=> Use `Void` rather than `()` in examples without references.

src/Test/StateMachine/Prototype.hs
it was printed as `(Var i) ← New`, rather than `$i ← New`
```
Couldn't linearise:
┌───────────────────────────┐
│ $3 ← New                  │
│                  ⟶ Opaque │
└───────────────────────────┘
┌─────────┐ │                
│ Inc $3  │ │                
│         │ │ ┌─────────────┐
│         │ │ │ Write $3 -2 │
│         │ │ │        ⟶ () │
│         │ │ └─────────────┘
│    ⟶ () │ │                
└─────────┘ │                
┌─────────┐ │                
│ Read $3 │ │                
│     ⟶ 1 │ │                
└─────────┘ │                
```
=> fix bound var

example/src/DieHard.hs, example/src/MutableReference.hs, example/src/TicketDispenser.hs, example/src/UnionFind.hs, src/Test/StateMachine.hs, src/Test/StateMachine/Internal/Parallel.hs, src/Test/StateMachine/Internal/Types.hs, src/Test/StateMachine/Types.hs
This change also exposes the types of `Fork` and `Program` but not its constructors, so at the moment one can only plug and play in a similar fashion as the property helpers anyway (unless one imports the `Internal`), but I think it is okay.
Maybe we should also expose `checkParallelInvariant`?
=> split out helper properties into more combinator style

example/quickcheck-state-machine-example.cabal, example/src/CircularBuffer.hs, example/src/CrudWebserverDb.hs, example/src/CrudWebserverFile.hs, example/src/DieHard.hs, example/src/MutableReference.hs, example/src/MutableReference/Prop.hs, example/src/TicketDispenser.hs, example/src/UnionFind.hs, example/stack.yaml, example/test/DieHardSpec.hs, example/test/HspecInstance.hs, example/test/MutableReferenceSpec.hs, example/test/TicketDispenserSpec.hs, quickcheck-state-machine.cabal, src/Test/StateMachine.hs, src/Test/StateMachine/Generics.hs, src/Test/StateMachine/Internal/Types.hs, src/Test/StateMachine/Internal/Utils.hs, src/Test/StateMachine/Types.hs, src/Test/StateMachine/Types/References.hs, stack.yaml
- Add variants of properties which return counterexamples, so we don't need to read them from strings anymore.
- Add a type class to recognize constructors. A TH script to write the instances is TODO.
- Fix `Show` instances. TODO: This makes traces pretty noisy, looking like `Write (Reference (Symbolic (Var 0))) 0` instead of `Write (Var 0) 0`. But instead of hijacking `Show`, it seems better to specify a custom printer of actions separately, via an explicit parameter or a different type class.
- Remove `Read` instances in examples and unused imports.
Fixes #157
=> Integrate Quickcheck with counterexamples

.travis.yml, src/Test/StateMachine/Internal/Parallel.hs
Previously, the library was getting built in the install phase, so the `--pedantic` flag for warning-free code only applied to examples.
Would you also like hlint to be added to CI?
=> Update travis script to not build the library in install phase

test/Spec.hs
They require docker to spin up postgres, and thus break on stackage.
Closes #222.
=> Disable webserver tests for now.

.travis.yml, test/Spec.hs
Suggested here: https://github.com/haskell/cabal/issues/2546
=> Try the -j1 flag to stop travis from running out of memory.

quickcheck-state-machine.cabal, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, test/CrudWebserverDb.hs, test/Echo.hs
* Replace `MonadBaseControl IO m` with `MonadUnliftIO m`. Reasoning: see the  documentation for [`unliftio`](http://hackage.haskell.org/package/unliftio).
* Replace `liftBaseWith (const ..)` with `liftIO ..`. This means that these  `MonadBaseControl IO m` constraints can be simplified to `MonadIO m`  constraints.
* Remove manual `liftIO`s where possible by using lifted functions from  `unliftio`.
* Replace the uses of lifted functions from `lifted-async` by the  corresponding lifted variants from `unliftio`.
* Replace the uses of functions from `stm` by the corresponding lifted  variants from `unliftio`.
=> Replace MonadBaseControl IO with MonadUnliftIO

src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Types.hs, test/MemoryReference.hs
Consider shrinking a set of commands such as
```haskell
Commands [
Command cmd1           (S.fromList [Var 0])
, Command cmd2           (S.fromList [Var 1])
, Command (cmd3 (Var 1)) (S.fromList [])
]
```
Shrinking is basically a call to QuickCheck's `shrinkList` followed by a
validation step, the core of which is implemented in `validCommands`.
`validCommands` executes each command, checking preconditions, and checking
which variables are in scope, and (effectively) renaming variables. For
example, given the shrink candidate
```haskell
Commands [
-- first command deleted
Command cmd2           (S.fromList [Var 1])
, Command (cmd3 (Var 1)) (S.fromList [])
]
```
`validCommands` will reexecute `cmd2`, find all is well, construct
```haskell
Command cmd2           (S.fromList [Var 0]) -- …
```
=> Fix important bug in shrinking

CHANGELOG.md, LICENSE, README.md, quickcheck-state-machine.cabal
* Update the changelog.
* Bump copyright year and add new contributors to license file.
* Bump version and copyright year in cabal file.
* Fix typo and start list of real world examples in readme.
=> Prepare for v0.5.0 release. [skip ci]

src/Test/StateMachine.hs, src/Test/StateMachine/ConstructorName.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, test/CircularBuffer.hs, test/CrudWebserverDb.hs, test/DieHard.hs, test/Echo.hs, test/ErrorEncountered.hs, test/MemoryReference.hs, test/TicketDispenser.hs
@stevana , first of all, let me apologize for submitting another PR so soon after your release. As I am continuing to work on my example and getting very detailed about shrinking, I realized that there is another problem with the lib that makes it impossible for me to apply some of the techniques I've been using. The good news is that this is a minor change only; the bad news is that technically speaking it _is_ an API breaking change :/ 
Many top-level functions had constraints such as
```haskell
Generic1 cmd, GConName1 (Rep1 cmd)
```
This is however problematic when using commands for which `Generic1` instances
are difficult are impossible to derive or define. It is also somewhat
unidiomatic Haskell: typically we don't require `Generic1` (or `Generic`), and
then some function on the …
=> Generalize GConName

test/Echo.hs, test/Spec.hs, test/TicketDispenser.hs
Related Issue https://github.com/advancedtelematic/quickcheck-state-machine/issues/240
We use the same approach at iohk, to avoid using `ioPropery` for tests which need some initialization. `forAllCommands` needs a `StateMachine`, but never uses the semantics. So these semantics don't need to be initialized. What do you think?
We can see that tests now shrink:
```
parallel bad, see issue #218:                                  OK
+++ OK, failed as expected. Falsifiable (after 2 tests and 2 shrinks):
ParallelCommands
{ prefix =
Commands
{ unCommands =
[ Command
(In
"M`Yk\v<v5_:rc!% aex\930410Zh\DC1\1110845z8YP\DELW=1o\v9\920537\789089\SO\"Hqn\SUBkS\417326H~p]NS\219097\250984\&1kX\SYNv\153590\125848ijH^E\227605U8@\319153)\SUBlYhri\RS\1064709\&7`\CAN\SYN\f\216950\933519\615337\73182\&0:8J]-\88 …
```
=> remove ioProperty from tests

test/CrudWebserverDb.hs, test/Spec.hs
There is a problem with example in `test/CrudWebserverDb.hs` where it will sometimes try connecting to postgres before the database is ready. This PR prevents this by adding another health check and also makes sure that docker containers and volumes are properly cleaned up afterwards.
The new health check creates some noisy output that obscures test results (that are hard to read anyway tbh), so this PR is WIP, as I hope to address this issue as well.
=> [WIP] Fix/crud example docker

quickcheck-state-machine.cabal, src/Test/StateMachine/Markov.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Utils.hs, stack.yaml, test/ShrinkingProps.hs
And remove old CPP hacks to support older versions.
=> Depend on latest version of Quickcheck (2.13.1).

stack.yaml
The old format doesn't work with latest release of stack, and
breaks CI.
=> Migrate away from deprecated stack.yaml format.

README.md, src/Test/StateMachine.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Types/History.hs, test/MemoryReference.hs, test/Spec.hs
=> Towards being able to handle crashing processes.

quickcheck-state-machine.cabal, src/Test/StateMachine/DotDrawing.hs, test/Overflow.hs, test/Spec.hs
> Can you think of an example bug which only manifests itself when 3 or more threads are used? Would be > nice to have such an example, but doesn't have to be part of this PR.
This is an example which only manifests when there are >= 4 threads.
The Model is a set of references of Int8. Some commands pick a random reference and add a constant number (in an atomic way) and then substract the same number (in an atomic way). If there are many threads the result can overflow.
Check also how commands are shrunk to sum to 128 (which is the minimum overflow point)
=> Add Overflow example which fails only with >=4 threads

test/ShrinkingProps.hs
Related issue https://github.com/advancedtelematic/quickcheck-state-machine/issues/327
I think the issue is that ShrinkProps sometimes create too many references, so I used an upper limit. I believe this does not reduce too much the power of testing.
=> fix ci times

test/CrudWebserverDb.hs, test/ErrorEncountered.hs, test/ShrinkingProps.hs
Related issue https://github.com/advancedtelematic/quickcheck-state-machine/issues/327
Note how this exception, which appears very often is most of the times hidden because of laziness:
```
> undefined `Prelude.elem` []
False
```
So the generation creates the exception many times, but the precondition hides it, since it never evaluates the undefined thunk.
=> fix generators

test/Spec.hs
=> Rename overflow properties and bump maxSuccess for overflow.4-threads.

src/Test/StateMachine.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, test/MemoryReference.hs
This pr adds an addition, simple option for labelling sequential tests and also makes all option available for the parallel case (and also the n-parallel case). 
I replaced the existing tags with the new option, for the test which run on ci. Opinions on this? I think it reduces the verbosity.
We now have this:
```
prop_circularBuffer:                                           OK (0.06s)
+++ OK, passed 100 tests.
Commands (333 in total):
28.5% New
25.2% Len
24.9% Put
21.3% Get
```
instead of 
```
prop_circularBuffer:                                           OK (0.07s)
+++ OK, passed 100 tests:
74% coverage
7% []
3% [("New",1)]
2% [("Get",1),("Len",4),("New",1),("Put",1)]
2% [("New",1),("Put",1)]
1% [("Get",1),("Len",12),("New",2),("Put",2)]
1% [("Get",1),("Len",12),("New",2),("Put",7)]
1% …
```
=> Labelling improvements

src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Types.hs
Related issue: https://github.com/advancedtelematic/quickcheck-state-machine/issues/340
I have found this quite useful while debugging. It prints exactly which exception was thrown while running the semantics:
`ExceptionThrown "\"user error (failed)\"" /= Ok`
instead of
`ExceptionThrown /= Ok `
=> Show which exception was thrown

test/Spec.hs
As we are still seeing this fail sometimes on CI:
https://travis-ci.org/advancedtelematic/quickcheck-state-machine/jobs/563426231#L1015
=> Bump maxSuccess from 6000 to 10000 for CrashAndLogicBugParallel.

quickcheck-state-machine.cabal, src/Test/StateMachine/Parallel.hs, test/Mock.hs, test/Spec.hs
This pr fixes what I think is an issue related to the mock function in the parallel case. It also adds a new example, which fails without the fix. The test is pretty simple: we model a system from which you can only try to create some references:
```
data Command r
= Create
```
The system manages to create only the first reference:
```
data Response r
= Created (Reference Int r)
| NotCreated
```
The sequential case works well, but in the paralle case if two commands try to create a reference in parallel, like in the example below, we don't know which one will succeed.
```
ParallelCommands
{ prefix = Commands { unCommands = [] }
, suffixes =
[ Pair
{ proj1 =
Commands
{ unCommands =
[ Command Create (Created (Reference (Symbolic (Var 0)))) [ Var 0 ]
]
}
, proj2 =
Commands { unCommands = [ …
```
=> fix Mock in parallel

.gitignore, quickcheck-state-machine.cabal, test/SQLite.hs, test/Schema.hs, test/Spec.hs
Add a new SQLite example. The semantics use SQLite in a bit different way than normal: all write request are serialized on a TBQueue and there is a single thread which takes them out of the queue and executes them.
I should note this test has some features borrowed from tests here https://github.com/input-output-hk/ouroboros-network and http://www.well-typed.com/blog/2019/01/qsm-in-depth/
=> Write thread sqlite

test/RQlite.hs
Otherwise cabal will confuse the RQLite module with the Rqlite module on
case-insensitive OS (like OSX).
=> Use PackageImports for Rqlite

quickcheck-state-machine.cabal, src/Test/StateMachine/Lockstep/Aux.hs, src/Test/StateMachine/Lockstep/NAry.hs, src/Test/StateMachine/Lockstep/Simple.hs, stack.yaml, test/IORefs.hs, test/RQlite.hs, test/Spec.hs
Submitting a draft PR to let you guys know we've been working on this and made quite a bit of progress. However, I am yet to use these abstractions in my real/large QSM test setup (or indeed in the QSM tests themselves that use the patterns from my blog post), so I'm sure a bit more further tweaking will be required. However, quite pleased with how this turned out.
This is joint work with Alfredo Di Napoli.
This captures the patterns described in http://www.well-typed.com/blog/2019/01/qsm-in-depth/ as a proper Haskell abstraction. The basic idea is that we have a concept of commands and responses (just like in the lower level API), along with two interpretors, one for the system under test and one for the model. We then compare that they can run in lockstep, comparing responses at every …
=> High-level interface to the state machine API

quickcheck-state-machine.cabal
In 81a6c1c8376d72c570bbfc65b626e67687c36d59 and a3050887cda78e216bc4222bccbc8594528cc637, the QuickCheck bound was bumped from 2.9.2 to 2.13.1 to 2.13.2, while 2.12 is already low enough.
=> Relax QuickCheck bound

src/Test/StateMachine/Sequential.hs
The top-level of a QSM test typically looks something like this:
```haskell
forAllCommands ... $ \cmds -> QC.monadicIO $ do
(hist, prop) <- .... runCommands ...
prettyCommands ...
```
The problem is that `runCommands` lives in PropertyM. This makes it impossible to do any kind of bracketing. Fortunately, it turns out that this use of `PropertyM` is actually not needed at all. In this commit, I remove it without having to change much at all, except having to insert a few extra runs in the test. In particular, the above will now turn into
```haskell
forAllCommands ... $ \cmds -> QC.monadicIO $ do
(hist, prop) <- .... run ( runCommands ... ) ...
prettyCommands ...
```
which, crucially, would allow us to do something like
```haskell
forAllCommands ... $ \cmds -> QC.monadicIO $ do
(hist, prop) …
```
=> Avoid unnecessary use of `run`

quickcheck-state-machine.cabal, src/Test/StateMachine/Lockstep/Auxiliary.hs, src/Test/StateMachine/Lockstep/NAry.hs, src/Test/StateMachine/Lockstep/Simple.hs
Even with an extension, the Aux filename is not allowed on Windows.
=> Rename Aux.hs to Auxiliary.hs
