advancedtelematic/quickcheck-state-machine

src/Test/QuickCheck/StateMachineModel.hs, test/Spec.hs
=> Refactor run/semantics to let the user choose which monad to run the

src/Test/QuickCheck/StateMachineModel.hs, test/Spec.hs
=> Remove scope/index from response; we can calculate it when pretty

quickcheck-state-machine.cabal
=> Add package constraints to cabal file based on the current stackage

example/src/DeviceUpdates.hs, example/src/MutableReference.hs, example/test/DieHardSpec.hs, src/Test/StateMachine.hs, src/Test/StateMachine/Internal/Parallel.hs, src/Test/StateMachine/Internal/Sequential.hs, src/Test/StateMachine/Internal/Types.hs, src/Test/StateMachine/Internal/Types/IntRef.hs, src/Test/StateMachine/Types.hs
```
Couldn't linearise:
Prefix:
New --> $0
Parallel:
1. Inc ($0) --> ()
Read ($0) --> 1
2. Inc ($0) --> ()
```
=> Have a nicer presentation of refs in ShowCmd

README.md
Won't work until we actually upload it...
=> Add hackage badge to readme [ci skip].

.travis.yml, example/src/TicketDispenser.hs
This PR tries to address issue #117.
@saurabhnanda: Does this help?
=> Document ticket dispenser's semantics function.

example/src/UnionFind.hs
=> Fix bug in generation precondition in the union/find example.

src/Test/StateMachine/Prototype.hs
So this shrink removes random commands, and then goes through and remove commands that uses vars that are no longer in scope or the precondition doesn't hold anymore for.
=> add shrinking

src/Test/StateMachine/Prototype.hs
For similar reason as we had a `String` for the `InvokationEvent` I added one for the `ResponseEvent`, this simplifies printing to boxes, as I don't have to go via the `Operation` type to know how to print the `Response`.  I also had to convert between the two types `Fork` and `Pid` but I made this very obvious via the import `INTERNAL`, this will be fixed later when we use proper things again.
Example output:
```
Couldn't linearise:
┌─────────────────────────────────────────┐
│ Var 0 <- New                            │
│                                ⟶ Opaque │
└─────────────────────────────────────────┘
┌─────────────────────────────────────────┐
│ Write (Var 0) 4                         │
│                                    ⟶ () │
└─────────────────────────────────────────┘ …
```
=> fix boxdrawing

example/src/MutableReference.hs, example/src/MutableReference/Prop.hs, example/src/UnionFind.hs, quickcheck-state-machine.cabal, src/Test/StateMachine/Types.hs, src/Test/StateMachine/Types/HFunctor.hs, src/Test/StateMachine/Types/References.hs
Relevant commit:
https://github.com/hedgehogqa/haskell-hedgehog/commit/2d3b17bd788798fb7d25205efbfd9dff0f2e6c74
=> Steal simpler references trick from hedgehog.

example/quickcheck-state-machine-example.cabal, example/src/CircularBuffer.hs, src/Test/StateMachine/Internal/Sequential.hs
=> Circular buffers example

CHANGELOG.md, LICENSE, README.md, example/src/CircularBuffer.hs
=> Add Lysxia to license file, update readme and changelog with circular

example/quickcheck-state-machine-example.cabal, example/src/CrudWebserverDb.hs, example/src/CrudWebserverFile.hs, example/src/TicketDispenser.hs, example/test/CrudWebserverDbSpec.hs, example/test/HspecInstance.hs, example/test/TicketDispenserSpec.hs
Makes better use of the temporary directory
=> Improve clean up of examples

CHANGELOG.md, quickcheck-state-machine.cabal, src/Test/StateMachine/Z.hs
The idea is to use this little language to define concise and showable models.
=> First go at Z inspried definition of relations and associcated operations.

quickcheck-state-machine.cabal
Candidate uploaded at: https://hackage.haskell.org/package/quickcheck-state-machine-0.2.0/candidate
=> Prepare for v0.2.0 release.

quickcheck-state-machine.cabal, src/Test/StateMachine/Logic.hs
This should be useful in pre- and post-conditions...
=> Add logic module which helps us print better counterexamples.

src/Test/StateMachine/Logic.hs
=> Add a module header to the logic module and a reference to one of the

CHANGELOG.md, quickcheck-state-machine.cabal
In order to easier keep up with Stackage nightly. Also prepare new
release.
=> Remove upper bounds for dependencies.

src/Test/StateMachine.hs
=> Add variant of actionNames that only gives back the constructors.

.travis.yml, example/src/CrudWebserverDb.hs, quickcheck-state-machine.cabal, src/Test/StateMachine/Internal/Types.hs, src/Test/StateMachine/Internal/Types/Environment.hs, src/Test/StateMachine/Types/History.hs, stack.yaml
Many of the dependencies that our examples use are not in nightly yet.
=> WIP: Make it work on stackage nightly.

quickcheck-state-machine.cabal, test/Echo.hs, test/Spec.hs
=> Add Damian Nadales' echo example from issue #218 to the test suite.

README.md, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Types/History.hs
=> Show counterexample when parallel property fails.

README.md
=> Explain mock better in the README.

quickcheck-state-machine.cabal, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Utils.hs
=> Add old QuickCheck cover combinator (see issue #248 for details).

quickcheck-state-machine.cabal, src/Test/StateMachine/ConstructorName.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Types.hs, src/Test/StateMachine/Utils.hs, test/CircularBuffer.hs, test/CrudWebserverDb.hs, test/DieHard.hs, test/Echo.hs, test/ErrorEncountered.hs, test/MemoryReference.hs, test/ShrinkingProps.hs, test/Spec.hs, test/TicketDispenser.hs
See #262 for discussion.
@stevana This is a WIP PR. This implements the generalization we previously discussed, but only for the sequential case. Submitting it as a PR now so you can take a look to see what you think. I've not yet tried the test suite (since that will require implementing the parallel case also), but I _have_ tested it in my real project and it works like a charm. As you can see in the PR, the update to the code is actually not that big either, which is good. 
I think tomorrow I will try to finish my own test case now that this is working and available before trying to update the parallel case. I've not used parallel testing very much yet so might be a little slower.
=> WIP: Generalize shrinking

src/Test/StateMachine/Logic.hs, test/CircularBuffer.hs, test/CrudWebserverDb.hs, test/ErrorEncountered.hs, test/MemoryReference.hs, test/ShrinkingProps.hs
=> Rename (not)Elem to (not)Member and generalise it to Foldable.

src/Test/StateMachine/Sequential.hs
=> We should check for the mock-semantic mismatch before writing the

quickcheck-state-machine.cabal, test/Hanoi.hs, test/Spec.hs
Works for N discs and 3 pegs, but realisticly more than 4 discs will
cause it to struggle. There is nothing smart about this method.
=> Add Tower of Hanoi example

LICENSE
Signed-off-by: Stevan Andjelkovic <stevan.andjelkovic@here.com>
=> Add Kostas and Adam to license file. [skip ci]

src/Test/StateMachine.hs, src/Test/StateMachine/Labelling.hs, src/Test/StateMachine/Sequential.hs, test/ProcessRegistry.hs
Signed-off-by: Stevan Andjelkovic <stevan.andjelkovic@here.com>
=> Add variant of prettyCommands that prints tags covered at each step.

README.md
Signed-off-by: Stevan Andjelkovic <stevana@users.noreply.github.com>
=> Add link to process registry example in README. [skip ci]

quickcheck-state-machine.cabal, test/Spec.hs
Also clean up the Spec module a bit.
=> Test suite doesn't build with latest persistent.

src/Test/StateMachine/Parallel.hs
This pr fixes a bug related to parallel shrinking. It resolves https://github.com/advancedtelematic/quickcheck-state-machine/issues/302 and helps https://github.com/advancedtelematic/quickcheck-state-machine/pull/294
The current issue is caused because in `shrinkAndValidateParallel` the model is advanced by the commands which are not remmaped. Take a look at the following example:
We have a valid MemoryReference command:
```
ParallelCommands
{ prefix =
Commands
{ unCommands =
[
Command Create (Created (Reference (Symbolic (Var 0)))) [ Var 0 ]
Command Create (Created (Reference (Symbolic (Var 1)))) [ Var 1 ]
]
}
, suffixes =
[  Pair
{ proj1 =
Commands
{ unCommands =
[ ]
}
, proj2 =
Commands
{ unCommands =
[ Command (Increment (Reference (Symbolic (Var 1)))) Incremented []
]
}
}
, Pair
{ …
```
=> Fix parallel shrinking

src/Test/StateMachine/Parallel.hs
Signed-off-by: Stevan Andjelkovic <stevana@users.noreply.github.com>
=> Make simplify work for empty interleavings, fixes #318.

src/Test/StateMachine/Sequential.hs
When q-s-m runs the semantics it catches all exceptions and tries to handle them. However it can also catch async exceptions caused by interrupts (^C) and consider them as test failures and try to shrink them. This is magnified when running sequential properties on the main thread or through ghci: In these cases the exception caught is `AsyncException UserInterrupt` and ignoring this exception means the program entirely ignores ^C. In other cases, for exampe when running test suites with `defaultMain` (like in Spec) or when running parallel properties the problem is less apparent because semantics run in some async-action: In these cases the main thread receives `AsyncException UserInterrupt` and sends `AsyncCancelled` to the async threads. The semantics will fail and try to shrink the …
=> Don't catch async exceptions

src/Test/StateMachine/Markov.hs, test/ProcessRegistry.hs
capturing the state/action probabilities of a markov chain
=> add stimulus matrix

.travis.yml, quickcheck-state-machine.cabal, src/Test/StateMachine.hs, src/Test/StateMachine/DotDrawing.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Sequential.hs, src/Test/StateMachine/Types.hs, src/Test/StateMachine/Types/GenSym.hs, src/Test/StateMachine/Types/History.hs, src/Test/StateMachine/Utils.hs, stack.yaml, stack_lts-11.yaml, test/CrudWebserverDb.hs, test/Echo.hs, test/ErrorEncountered.hs, test/MemoryReference.hs, test/ShrinkingProps.hs, test/Spec.hs, test/TicketDispenser.hs
This replaces https://github.com/advancedtelematic/quickcheck-state-machine/pull/294 which was getting old. I rebased on the last changes and added dot visualization.
=> Generalize parallelism and visualization

src/Test/StateMachine.hs, src/Test/StateMachine/Parallel.hs, src/Test/StateMachine/Types.hs
This implements what we discussed here https://github.com/advancedtelematic/quickcheck-state-machine/issues/326
I need to take another look if I did everything alright, so this is WIP for now.
=> Improve exceptions handling

README.md, quickcheck-state-machine.cabal, test/Bookstore.hs, test/Spec.hs
PostgreSQL simple app, that allows creating, updating and reading from
database.
Based on: http://propertesting.com/book_case_study_stateful_properties_with_a_bookstore.html
Signed-off-by: Adam Boniecki <adambonie@gmail.com>
=> Bookstore example from propertesting.com

src/Test/StateMachine/DotDrawing.hs
One the the things discussed here https://github.com/advancedtelematic/quickcheck-state-machine/issues/327
=>  Handle missing dot exceptions

test/Spec.hs
=> Bump maxSuccess for Bookstore properties that expectFailure.

src/Test/StateMachine/Markov.hs
The source node is in green and the sink is in red.
=> Add colours to the markovToDot output.

CHANGELOG.md, quickcheck-state-machine.cabal, src/Test/StateMachine/Parallel.hs, stack.yaml, stack_lts-11.yaml, test/Cleanup.hs, test/CrudWebserverDb.hs, test/Echo.hs, test/ErrorEncountered.hs, test/MemoryReference.hs, test/Mock.hs, test/Overflow.hs, test/RQlite.hs, test/SQLite.hs, test/ShrinkingProps.hs, test/Spec.hs, test/TicketDispenser.hs
A test for a distributed db called [rqlite](https://github.com/rqlite/rqlite). It uses this [client](https://github.com/kderme/hs-rqlite) and uses docker. It also supports various injected errors, like killing/responding nodes, disconnecting/reconnecting nodes, pausing/unpausing, delays. Clock skews is wip.
=> Rqlite test
